### ISSUE TITLE
output hasil perhitungan pada termite 

### ISSUE THREAD

**Issue by bostang** [bostang/kalkulatorIntegerFPGA#2]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/64513224/142980672-4be91a16-f3a5-40f9-b39a-e5c26d79d204.png">

selain menampilkan hasil perhitungan pada 7-segment, apakah kita juga tetap mau menampilkan hasil perhitungan pada termite juga?

**Comment by linggaaradhanas22** [comment]
Ehh  ini maksud kalimatnya gimana wkwkw?
